#!/usr/bin/env python

import sys

from rqt_gui.main import Main
from action_server_monitor.plot import Plot

plugin = 'action_server_monitor.plot.Plot'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Plot.add_arguments))
